[mypy]
python_version = 3.12
explicit_package_bases = True
mypy_path = .
warn_return_any = False
warn_unused_configs = True
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = True
disallow_untyped_decorators = True
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_no_return = True
warn_unreachable = True
strict_equality = True
disallow_any_generics = True
no_implicit_reexport = True
ignore_missing_imports = True

[mypy-src.gui.*]
disable_error_code =
    attr-defined,
    union-attr,
    arg-type,
    assignment,
    operator,
    unreachable,

[mypy-src.utils.icon_generator]
disable_error_code = assignment

[mypy-src.models.database,src.automation.scheduler,src.cli.cli,src.services.notification_service,src.api.service_manager,src.api.sms_service,src.models.contact_manager]
disable_error_code =
    union-attr,
    assignment,
    arg-type,
    return-value,
    index,
    name-defined,
    var-annotated,
    attr-defined,
    unreachable,
    call-arg,
    type-arg,
    operator,
